---
name: Deploy Packages

on:
  push:
    branches:
      - trunk

jobs:
  build-amd64:
    name: amd64 Package Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: secondlife/setup-nfpm@v3
      - name: Place GPG Key
        run: echo -n "$CONTENTS" > build-scripts/package-self-signatures/deb-key.gpg
        env:
          CONTENTS: ${{ secrets.DEB_KEY_CONTENTS }}
      - name: Package amd64
        run: ./build-scripts/package-self-signatures/package.sh
        env:
          NFPM_PASSPHRASE: ${{ secrets.NFPM_PASSPHRASE }}
      - name: Upload amd64 for later
        uses: actions/upload-artifact@v4
        with:
          name: debian-to-upload-1.27.5-4
          path: build-scripts/package-self-signatures/legacy-nginx_1.27.5~4_amd64.deb
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
          overwrite: true
  build-arm64:
    name: Check Package builds on arm64
    runs-on: ubuntu-24.04-arm
    needs: [build-amd64]
    steps:
      - uses: actions/checkout@v4
      - uses: secondlife/setup-nfpm@v3
      - name: Download x86 Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: debian-to-upload-1.27.5-4
          path: build-scripts/package-self-signatures/
      - name: Download Backblaze CLI for ARM64
        run: |
          sudo pip3 install --upgrade --ignore-installed --break-system-packages b2
      - name: Sync Previous APT Repo
        run: b2 sync b2://${B2_BUCKET}/ ./apt/ --exclude-regex "conf/distributions"
        env:
          B2_BUCKET: ${{ secrets.APT_B2_BUCKET }}
          B2_APPLICATION_KEY_ID: ${{ secrets.APT_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.APT_KEY }}
      - name: Place down GPG Key
        run: echo -n "$CONTENTS" > build-scripts/package-self-signatures/deb-key.gpg
        env:
          CONTENTS: ${{ secrets.DEB_KEY_CONTENTS }}
      - name: Package ARM64
        run: ./build-scripts/package-self-signatures/package.sh
        env:
          NFPM_PASSPHRASE: ${{ secrets.NFPM_PASSPHRASE }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_REPREPRO_KEY }}
          passphrase: ${{ secrets.REPREPRO_GPG_PASSPHRASE }}
      - name: Add Packages to APT Repo
        run: |
          sudo apt install -y reprepro
          reprepro -b ./apt/ --architecture amd64 includedeb production ./build-scripts/package-self-signatures/legacy-nginx_1.27.5~4_amd64.deb
          reprepro -b ./apt/ --architecture arm64 includedeb production ./build-scripts/package-self-signatures/legacy-nginx_1.27.5~4_arm64.deb
      - name: Sync APT Repo
        run: b2 sync ./apt/ b2://${B2_BUCKET}/
        env:
          B2_BUCKET: ${{ secrets.APT_B2_BUCKET }}
          B2_APPLICATION_KEY_ID: ${{ secrets.APT_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.APT_KEY }}
  upload-docker:
    name: Publish Docker Image
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Legacy-nginx image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: remverse/legacy-nginx:latest,remverse/legacy-nginx:1.27,remverse/legacy-nginx:1.27.5